name: Deploy to Vercel
on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions: write-all

    steps:
      - uses: actions/checkout@v4

      - name: Set up Vercel environment variables
        uses: dkershner6/vercel-set-env-action@v3
        with:
          token: ${{ secrets.VERCEL_TOKEN }}
          projectName: ajisalit-backend
          envVariableKeys: MONGO_URL,JWT_SECRET
        env:
          MONGO_URL: ${{ secrets.MONGO_URL }}
          TARGET_MONGO_URL: preview,development,production
          TYPE_MONGO_URL: encrypted

          JWT_SECRET: ${{ secrets.JWT_SECRET }}
          TARGET_JWT_SECRET: preview,development,production
          TYPE_JWT_SECRET: encrypted
      
      - name: Deploy to Vercel
        uses: amondnet/vercel-action@v20
        with:
          vercel-token: ${{ secrets.VERCEL_TOKEN }}
          github-token: ${{ secrets.GITHUB_TOKEN }}
          vercel-args: '--prod'
          vercel-org-id: ${{ secrets.ORG_ID }}
          vercel-project-id: ${{ secrets.PROJECT_ID }}